api_version = "2024-07"

[[extensions]]
name = "t:name"
handle = "order-discount-rust"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "purchase.order-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = "cargo wasi build --release"
  path = "target/wasm32-wasi/release/order-discount-rust.wasm"
  watch = [ "src/**/*.rs" ]

  [extensions.ui.paths]
  create = "/"
  details = "/"
