api_version = "2024-07"

[[extensions]]
name = "t:name"
handle = "order-discount"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "purchase.order-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

# [START block-extension.configuration]
  [extensions.ui.paths]
  create = "/app/minimum-subtotal/:functionId/new"
  details = "/app/minimum-subtotal/:functionId/:id"
# [END block-extension.configuration]
